apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspace-app
  namespace: myspace-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspace-app
  template:
    metadata:
      labels:
        app: myspace-app
    spec:
      containers:
      - name: myspace-app
        image: nnksantosh/webpage-1:latest

        ports:
        - containerPort: 80