apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspace-app
  namespace: myspace-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspace-app
  template:
    metadata:
      labels:
        app: myspace-app
    spec:
      containers:
      - name: myspace-app
        image: nnksantosh/webpage-1:974ebfbe274403a9556b41888239e90f94b16a2f

        ports:
        - containerPort: 80