# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: webpage-1-ingress
#   namespace: webpage-1
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod

# spec:
#   ingressClassName: nginx

#   tls:
#   - hosts:
#     - mywebapage.site
#     secretName: webpage-1-tls

#   rules:
#   - host: mywebapage.site
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: webpage-1-service
#             port:
#               number: 80
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: webpage-ingress
  namespace: webpage-1

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - mywebapage.site
    secretName: webpage-tls

  rules:
  - host: mywebapage.site

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: webpage-service

            port:
              number: 80