apiVersion: v1
kind: Service

metadata:
  name: myspace-service
  namespace: myspace-website

spec:
  selector:
    app: myspace-app

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

  type: ClusterIP