name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: webpage-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # Checkout Code
    - name: Checkout
      uses: actions/checkout@v4

    # DockerHub Login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --no-cache \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
          -f docker/Dockerfile \
          --push .

    # Replace Docker Username
    - name: Replace Docker Username
      run: |
        sed -i 's|DOCKER_USERNAME|${{ secrets.DOCKER_USERNAME }}|g' k8s/base/deployment.yaml

    # Replace Image Tag
    - name: Replace Image Tag
      run: |
        sed -i 's|IMAGE_TAG|${{ github.sha }}|g' k8s/base/deployment.yaml

    - name: Commit Updated Manifest
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add k8s/base/deployment.yaml

        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"

        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/ProActive-Cloud-DevOps/New-Website_santosh.git

        git push origin HEAD:main
        
#--------------------------------------------------------Old

# name: Build and Deploy to EKS

# on:
#   push:
#     branches:
#       - main

# env:
#   IMAGE_NAME: webpage-1
#   AWS_REGION: ap-south-1
#   EKS_CLUSTER: workspace

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:

#     # Checkout Code
#     - name: Checkout
#       uses: actions/checkout@v4

#     # DockerHub Login
#     - name: Login to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     # Build and Push Docker Image
#     - name: Build and Push Docker Image
#       run: |
#         docker buildx build \
#           --platform linux/amd64 \
#           --no-cache \
#           -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
#           -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
#           -f docker/Dockerfile \
#           --push .

#     # Replace Docker Username
#     - name: Replace Docker Username
#       run: |
#         sed -i 's|DOCKER_USERNAME|${{ secrets.DOCKER_USERNAME }}|g' k8s/base/deployment.yaml

#     # Replace Image Tag
#     - name: Replace Image Tag
#       run: |
#         sed -i 's|IMAGE_TAG|${{ github.sha }}|g' k8s/base/deployment.yaml

#     # Configure AWS Credentials
#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

#     # Install kubectl
#     - name: Install kubectl
#       uses: azure/setup-kubectl@v4

#     # Connect to EKS
#     - name: Update kubeconfig
#       run: |
#         aws eks update-kubeconfig \
#           --region ${{ env.AWS_REGION }} \
#           --name ${{ env.EKS_CLUSTER }}

#     # # Deploy to Kubernetes
#     # - name: Deploy to EKS
#     #   run: |
#     #     kubectl apply -f k8s/base/namespace.yaml
#     #     kubectl apply -f k8s/base/service.yaml
#     #     kubectl apply -f k8s/base/ingress.yaml
#     #     kubectl apply -f k8s/base/deployment.yaml
 
#     # - name: Update Kubernetes Image
#     #   run: |
#     #     kubectl set image deployment/myspace-app \
#     #       myspace-app=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
#     #       -n myspace-website        
#     # Restart Deployment
#     # - name: Restart Deployment
#     #   run: |
#     #     kubectl rollout restart deployment myspace-app -n myspace-website

#     # # Verify Deployment
#     # - name: Verify Deployment
#     #   run: |
#     #     kubectl get pods -n myspace-website

        
    